import{NgModule}from'@angular/core';
import{CommonModule}from'@angular/common';
import{MatIconModule}from'@angular/material/icon';

import{SharedModule}from'../../../shared/shared.module';
import{SectionsRoutingModule}from'./sections-routing.module';

import{CategoriesSectionComponent}from'./categories-section/categories-section.component';
import{FeaturedTestsSectionComponent}from'./featured-tests-section/featured-tests-section.component';
import{HeroSectionComponent}from'./hero-section/hero-section.component';
import{OffersSectionComponent}from'./offers-section/offers-section.component';
import{PackagesSectionComponent}from'./packages-section/packages-section.component';
import{TestimonialsSectionComponent}from'./testimonials-section/testimonials-section.component';
import{TrustSectionComponent}from'./trust-section/trust-section.component';

@NgModule({
declarations:[
HeroSectionComponent,
CategoriesSectionComponent,
FeaturedTestsSectionComponent,
PackagesSectionComponent,
OffersSectionComponent,
TrustSectionComponent,
TestimonialsSectionComponent
],
imports:[CommonModule,SharedModule,MatIconModule,SectionsRoutingModule],
exports:[
HeroSectionComponent,
CategoriesSectionComponent,
FeaturedTestsSectionComponent,
PackagesSectionComponent,
OffersSectionComponent,
TrustSectionComponent,
TestimonialsSectionComponent
],
})
export
class
SectionsModule{}
